$ANSIBLE_VAULT;1.1;AES256
35353532376136303461316365653763326162333430333064623264643766666263656661383164
3664643535656434636339633834643333666163323032380a313536393163663964393561333062
65396135346561373134343664363966323138653838343464363461323233363436356565303839
3738353437333637310a323539376261646365373465386137653636636233633662316432636231
61343562663566373662333364306339326535356665613033353935306438643836626234303936
35316336313231626666326434613834323332613530633961376163323531373637336230646330
65326332366161323537666631333035663761303037303438633039323738336233643538333335
38396362623835316364383462366439306162366366373634643631386539366363343634653339
64623636643137313265616433383930626132386433356664663432326435643236393965306162
32633735666134343339373638666633643137393366633639306663383737373539636630326330
39313565623031663165643633386235343962386663613839306366303234633561363439613235
37663735376435383730363832633033353732646165383066626434373638646563653963353662
35353830663261643464333538613634623238653531343764356237323332326562393163353565
32636662326361343662316430636539623136613033346239366436396164343034373134633331
37663762313863643035393066393564343734343239366238616263376638663236316261666331
62316230346266316630303039633336396136363662303763626265353463363630383064323433
30646665346331333165353064313164643333653661313964323161653437326438356163366336
3863333462626362653232333265633132363434666561316631
